### ISSUE TITLE
div zonder id of class

### ISSUE THREAD

**Issue by Seijno** [lemuelmgsn/the-startup-responsive-interactieve-website#1]
`   <div>filter</div> `
ik zou er een waarde aan zetten zodat het duidelijker is wat het doet.

**Comment by lemuelmgsn** [comment]
https://github.com/lemuelmgsn/the-startup-responsive-interactieve-website/blob/b8bf7a21e803f6979c84216e347bece3d91eaff8/index.html#L32-L35

Ik heb het voor nu in een comment gezet omdat ik de filter pas later ga doen.
