### ISSUE TITLE
Foutieve datumnotatie in HTML.. 🐰

### ISSUE THREAD

**Issue by MisahSaid** [lemuelmgsn/the-startup-responsive-interactieve-website#10]
**Foutomschrijving**:
Er is een foutje met betrekking tot hoe je de datum heb genoteerd.

**Huidige code:**
https://github.com/lemuelmgsn/the-startup-responsive-interactieve-website/blob/55cae7242012124a88c78c76d647c901ee646c69/index.html#L78

Probleem:
De juiste manier van het noteren van 'datetime' is 'YYYY-MM-DD**T**HH:MM:SS'.

De 'T' is geeft een scheiding aan tussen de datum en de tijd.

Conclusie --> er ontbreekt een T in deze regel code.

Aanbeloven oplossing:
`<time datetime="2023-11-30T00:00:00+0000">
`

**Comment by lemuelmgsn** [comment]
https://github.com/lemuelmgsn/the-startup-responsive-interactieve-website/blob/689443359ca71648f270d9aaa2741746c7c6b4b7/index.html#L43

https://github.com/lemuelmgsn/the-startup-responsive-interactieve-website/blob/689443359ca71648f270d9aaa2741746c7c6b4b7/index.html#L56

https://github.com/lemuelmgsn/the-startup-responsive-interactieve-website/blob/689443359ca71648f270d9aaa2741746c7c6b4b7/index.html#L69

https://github.com/lemuelmgsn/the-startup-responsive-interactieve-website/blob/689443359ca71648f270d9aaa2741746c7c6b4b7/index.html#L82

https://github.com/lemuelmgsn/the-startup-responsive-interactieve-website/blob/689443359ca71648f270d9aaa2741746c7c6b4b7/index.html#L95

Ook gefixt!
