### ISSUE TITLE
Tipje: Data en tijd format

### ISSUE THREAD

**Issue by xxdaniquee** [lemuelmgsn/the-startup-responsive-interactieve-website#11]
https://github.com/lemuelmgsn/the-startup-responsive-interactieve-website/blob/55cae7242012124a88c78c76d647c901ee646c69/index.html#L52

Dit is een geldig datum- en tijdformaat, maar het zou handiger kunnen zijn om het ISO 8601-formaat te gebruiken.
Dan zet je een T voor de tijd. Aan het einde een Z voor Universal Time

Hier staat meer informatie over het ISO 8601 format: https://www.ionos.com/digitalguide/websites/web-development/iso-8601/

**Comment by lemuelmgsn** [comment]
https://github.com/lemuelmgsn/the-startup-responsive-interactieve-website/blob/689443359ca71648f270d9aaa2741746c7c6b4b7/index.html#L43

Gefixt!
