### ISSUE TITLE
MDN - <header>  🐲

### ISSUE THREAD

**Issue by MisahSaid** [lemuelmgsn/the-startup-responsive-interactieve-website#12]
**Wat merkte ik op?**
Ik zie dat je geen gebruikt maakt van de `<header>` element. 

**Huidige code:**
https://github.com/lemuelmgsn/the-startup-responsive-interactieve-website/blob/55cae7242012124a88c78c76d647c901ee646c69/index.html#L1-L28

'**oplossing**':
Misschien zou je kunnen kijken of je:
https://github.com/lemuelmgsn/the-startup-responsive-interactieve-website/blob/55cae7242012124a88c78c76d647c901ee646c69/index.html#L26-L28

kunt verwerken in een `<header>` element (of in plaats van section het een header te maken) om de html semantischer te maken.

**Comment by lemuelmgsn** [comment]
https://github.com/lemuelmgsn/the-startup-responsive-interactieve-website/blob/28a313093c3ba86ba112a416e54e510e1e91e15d/index.html#L28-L31

Ik heb er een header van gemaakt!
