### ISSUE TITLE
Headings ontbreken 

### ISSUE THREAD

**Issue by Jason2426** [lemuelmgsn/the-startup-responsive-interactieve-website#14]
Misschien zitten er weinig titels, subtitels, of kopteksten in het design maar misschien is dit wel handig om toe te voegen zodat de gebruiker weet waar een section voor staat en wat die er kan lezen of doen.  Vaak is de regel minimaal een h1 element op de site. Bij de cards in de carousel doe je het wel maar misschien handig om een heading toe te voegen boven de carousel of het eerste stukje text in de main. 

https://github.com/lemuelmgsn/the-startup-responsive-interactieve-website/blob/55cae7242012124a88c78c76d647c901ee646c69/index.html#L25-L114

Maak bijvoorbeeld hier een h1 van : https://github.com/lemuelmgsn/the-startup-responsive-interactieve-website/blob/55cae7242012124a88c78c76d647c901ee646c69/index.html#L27

Of voeg hier bijvoorbeeld een heading aan toe "Articles to read" of iets in die zin zodat de gebruiker weet wat de items in de carousel zijn.  

[Lees hier waarom het goed is en hoe je het oplost](https://dequeuniversity.com/rules/axe/4.1/page-has-heading-one#:~:text=Generally%2C%20it%20is%20a%20best,contains%20only%20one%20h1%20element.)

**Oplossing** : Titels, subtitels of kopteksten toevoegen aan het design en toevoegen aan je HTML.

**Comment by lemuelmgsn** [comment]
https://github.com/lemuelmgsn/the-startup-responsive-interactieve-website/blob/689443359ca71648f270d9aaa2741746c7c6b4b7/index.html#L27-L37

Gefixt! ik heb van de eerste section een header van gemaakt en de ander heb ik een h1 en een h2 gegeven.
