### ISSUE TITLE
HTML Inspringen Top

### ISSUE THREAD

**Issue by Jason2426** [lemuelmgsn/the-startup-responsive-interactieve-website#15]
Je HTML is erg goed leesbaar 👏  goed ingesprongen en geen onnodige HTML. 

https://github.com/lemuelmgsn/the-startup-responsive-interactieve-website/blob/55cae7242012124a88c78c76d647c901ee646c69/index.html#L12-L116

**Comment by lemuelmgsn** [comment]
Thx gang
