### ISSUE TITLE
 Overweeg het h1-element alleen als kop op het hoogste niveau te gebruiken

### ISSUE THREAD

**Issue by Abeeryu** [lemuelmgsn/the-startup-responsive-interactieve-website#17]
https://github.com/lemuelmgsn/the-startup-responsive-interactieve-website/blob/689443359ca71648f270d9aaa2741746c7c6b4b7/index.html#L29

https://github.com/lemuelmgsn/the-startup-responsive-interactieve-website/blob/689443359ca71648f270d9aaa2741746c7c6b4b7/index.html#L37

Het is beter om h1 element alleen aan het begin van jouw website gebruiken als groot element, daarna kan je voor de rest h2 gebruiken.

Bron:
https://smartranking.nl/html-headings/#:~:text=De%20H1%20heading%20is%20de,je%20H1%20heading%20te%20zetten.

**Comment by lemuelmgsn** [comment]
https://github.com/lemuelmgsn/the-startup-responsive-interactieve-website/blob/28a313093c3ba86ba112a416e54e510e1e91e15d/index.html#L28-L38

Gefixt!
