### ISSUE TITLE
Div

### ISSUE THREAD

**Issue by zainablfz** [lemuelmgsn/the-startup-responsive-interactieve-website#4]
Het ziet er tot nu toe goed uit! Je code is overzichtelijk. 

Alleen zou ik niet een ``<div>`` om filter heen zetten, tenzij je er een class bij gaat gebruiken. 

Dit gaat om: ``<div>filter</div>``

**Comment by lemuelmgsn** [comment]
https://github.com/lemuelmgsn/the-startup-responsive-interactieve-website/blob/b8bf7a21e803f6979c84216e347bece3d91eaff8/index.html#L32-L35

Ik heb er nu een class name voor gebruikt, alleen heb ik het wel in comments gezet omdat ik pas later aan de filter ga werken!
