### ISSUE TITLE
Section zonder H element

### ISSUE THREAD

**Issue by xxdaniquee** [lemuelmgsn/the-startup-responsive-interactieve-website#8]
`<section> 
        <p>Hey! We're GRRR, a Creative Digital Agency based in Amsterdam. <br> <br> Welcome to our tech blog, where we share our thoughts and experiments.</p>
    </section>`
https://github.com/lemuelmgsn/the-startup-responsive-interactieve-website/blob/55cae7242012124a88c78c76d647c901ee646c69/index.html#L26C5-L28C15

In deze section heb je geen H element gebruikt. Er zijn 2 opties om dit op te lossen:
1. Een H element toevoegen
2. Een div ervan maken.

Hier is meer info :) https://www.w3docs.com/snippets/html/what-is-the-difference-between-section-and-div-elements.html

**Comment by lemuelmgsn** [comment]
https://github.com/lemuelmgsn/the-startup-responsive-interactieve-website/blob/689443359ca71648f270d9aaa2741746c7c6b4b7/index.html#L28-L37

Ik heb de nu section veranderd in een header. Daarnaast heb ik de volgende section wel een h1 gegeven.
