### ISSUE TITLE
Foutieve datumnotatie in HTML-document 🍊

### ISSUE THREAD

**Issue by MisahSaid** [lemuelmgsn/the-startup-responsive-interactieve-website#9]
**Foutmelding**:
Er is een foutje in de HTML op regel 65. De huidige datumnotatie is onjuist. 

Het correcte formaat voor de datumnotatie is 'YYYY-MM-DD', maar in de code staat 'YYYY-MM-D'.

**Huidige code:**
https://github.com/lemuelmgsn/the-startup-responsive-interactieve-website/blob/55cae7242012124a88c78c76d647c901ee646c69/index.html#L65

**Aanbeloven aanpassing:**
``
<time datetime="2021-08-01 00:00:00 +0000 UTC">
``

**Comment by lemuelmgsn** [comment]
https://github.com/lemuelmgsn/the-startup-responsive-interactieve-website/blob/689443359ca71648f270d9aaa2741746c7c6b4b7/index.html#L69

Gefixt!
